version: 2
jobs:
  lint:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/oxyno-zeta/s3-proxy
    steps:
      - checkout
      - run: make lint
      - save_cache:
          key: go-mod-{{ checksum "go.mod"  }}
          paths:
            - "/go/pkg/"
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/oxyno-zeta/s3-proxy
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make build
  build-cross:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/oxyno-zeta/s3-proxy
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make build-cross
  test:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/oxyno-zeta/s3-proxy
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make test
workflows:
  version: 2
  project:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - build-cross:
          requires:
            - lint
      - test:
          requires:
            - lint
